language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services: mongodb

before_script:
  - sleep 15
before_install: echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install: travis_retry composer update --no-interaction --no-progress --no-suggest --prefer-stable
